jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest / macos-latest>
    steps:
      - name: Convertisseur de degrée
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'src/build.spec'
          requirements: 'src/requirements.txt'
          options: --onefile, --name "My App", --windowed, 
